# Generated by Django 3.2 on 2022-12-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='building_com.block'),
            preserve_default=False,
        ),
    ]
