# Generated by Django 3.2 on 2022-12-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_com', '0002_clients_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='floor',
            field=models.IntegerField(default=7),
        ),
    ]
